#!/bin/sh

# luci language
uci set luci.main.lang=zh_cn
uci commit luci

#
/etc/init.d/dnscrypt-proxy stop


# system
uci batch <<EOF
set system.@system[0].hostname='HyperV_vm'
set system.@system[0].timezone='PST8PDT,M3.2.0,M11.1.0'
set system.@system[0].zonename='America/Los Angeles'
delete system.ntp.enable_server
set system.ntp.server="cn.ntp.org.cn"
add_list system.ntp.server="edu.ntp.org.cn"
add_list system.ntp.server="ntp.ntsc.ac.cn"
add_list system.ntp.server="ntp.tuna.tsinghua.edu.cn"
set system.ntp.use_dhcp='0'
EOF
uci commit system


# network config
uci batch <<EOF
delete network.lan.ip6assign
delete network.globals.ula_prefix
set network.globals.packet_steering='1'
set network.lan.gateway='192.168.177.1'
set network.lan.dns='127.0.0.1'
set network.lan6=interface
set network.lan6.proto='dhcpv6'
set network.lan6.device='@lan'
set network.lan6.reqaddress='try'
set network.lan6.reqprefix='auto'
set network.lan2=interface
set network.lan2.proto='static'
set network.lan2.device='br-lan'
set network.lan2.ipaddr='192.168.177.78'
set network.lan2.netmask='255.255.255.0'
set network.lan2.gateway='192.168.177.1'
set network.lan2.metric='40'
set network.lan2.dns='127.0.0.1'
set network.lan3=interface
set network.lan3.proto='static'
set network.lan3.device='br-lan'
set network.lan3.ipaddr='192.168.177.79'
set network.lan3.netmask='255.255.255.0'
set network.lan3.gateway='192.168.177.1'
set network.lan3.dns='127.0.0.1'
set network.lan3.metric='40'
EOF
uci commit network
/etc/init.d/network restart


# firewall
uci batch <<EOF
delete firewall.@defaults[0].syn_flood='0'
set firewall.@defaults[0].input='ACCEPT'
set firewall.@defaults[0].forward='ACCEPT'
set firewall.@defaults[0].fullcone6='1'
delete firewall.@zone[0].network
add_list firewall.@zone[0].network='lan'
add_list firewall.@zone[0].network='lan6'
add_list firewall.@zone[0].network='lan2'
add_list firewall.@zone[0].network='lan3'
EOF
uci commit firewall
/etc/init.d/firewall restart



# DHCP & dnsmasq
uci batch <<EOF
set dhcp.@dnsmasq[0].boguspriv='1'
set dhcp.@dnsmasq[0].dns_redirect='0'
set dhcp.@dnsmasq[0].expandhosts='0'
set dhcp.@dnsmasq[0].authoritative='0'
set dhcp.@dnsmasq[0].interface='lan'
set dhcp.@dnsmasq[0].dnsseccheckunsigned='0'
set dhcp.@dnsmasq[0].filter_aaaa='1'
set dhcp.@dnsmasq[0].nonegcache='1'
delete dhcp.lan.dhcpv6
delete dhcp.lan.ra
delete dhcp.lan.ra_slaac
delete dhcp.lan.ra_flags
delete dhcp.lan.ndp
set dhcp.lan.ignore='1'
set dhcp.lan.dynamicdhcp='0'
set dhcp.@dnsmasq[0].server='127.0.0.1#5335'
EOF
uci commit dhcp
/etc/init.d/dnsmasq restart


#mosdns
uci batch <<EOF
set mosdns.config.enabled='1'
set mosdns.config.listen_port='5335'
set mosdns.config.geo_auto_update='1'
set mosdns.config.geo_update_week_time='1'
set mosdns.config.geo_update_day_time='2'
set mosdns.config.dump_file='1'
set mosdns.config.concurrent='2'
set mosdns.config.custom_local_dns='1'
set mosdns.config.dns_leak='1'
set mosdns.config.bootstrap_dns='8.8.8.8'
set mosdns.config.local_dns='114.114.114.114'
add_list mosdns.config.local_dns='223.5.5.5'
set mosdns.config.remote_dns='udp://127.0.0.53:53'
set mosdns.config.enable_ecs_remote='0'
set mosdns.config.dump_interval='3600'
EOF
uci commit mosdns
/etc/init.d/mosdns restart


# fix distfeeds
cat << "EOF" > /etc/opkg/distfeeds.conf
src/gz immortalwrt_core https://downloads.immortalwrt.org/snapshots/targets/x86/64/packages
src/gz immortalwrt_base https://downloads.immortalwrt.org/snapshots/packages/x86_64/base
src/gz immortalwrt_luci https://downloads.immortalwrt.org/snapshots/packages/x86_64/luci
src/gz immortalwrt_packages https://downloads.immortalwrt.org/snapshots/packages/x86_64/packages
src/gz immortalwrt_routing https://downloads.immortalwrt.org/snapshots/packages/x86_64/routing
src/gz immortalwrt_telephony https://downloads.immortalwrt.org/snapshots/packages/x86_64/telephony
EOF


# argon
uci batch <<EOF
set argon.@global[0].primary='#1c78ff'
set argon.@global[0].dark_primary='#1c78ff'
set argon.@global[0].blur='10'
set argon.@global[0].blur_dark='10'
set argon.@global[0].transparency='0.5'
set argon.@global[0].transparency_dark='0.5'
set argon.@global[0].mode='normal'
set argon.@global[0].online_wallpaper='none'
EOF
uci commit argon


# ttyd autologin
#sed -i '65s/^#//g' /etc/init.d/ttyd
#uci set ttyd.@ttyd[0].interface='@lan'
#uci set ttyd.@ttyd[0].command='/bin/login -f root'
#uci commit ttyd
#/etc/init.d/ttyd restart


# turboacc
#uci batch <<EOF
#set turboacc.config.bbr_cca='1'
#set turboacc.config.fullcone6='0'
#set turboacc.config.hw_wed='0'
#EOF
#uci commit turboacc


# netspeedtest homebox is on
# uci set netspeedtest.homebox.enabled='1'
# uci set netspeedtest.speedtestiperf3.enabled='1'
# uci commit netspeedtest


# dropbear
uci commit dropbear
/etc/init.d/dropbear restart


#
/etc/init.d/dnscrypt-proxy start


exit 0

