#!/bin/bash

/etc/init.d/dnscrypt-proxy stop
uci commit system
uci commit network
#/etc/init.d/network restart
uci commit firewall
#/etc/init.d/firewall restart
uci commit dhcp
#/etc/init.d/dnsmasq restart
uci commit mosdns
#/etc/init.d/mosdns restart
uci commit argon
uci commit dropbear
/etc/init.d/dnscrypt-proxy start

exit 0
