#!/bin/bash

/etc/init.d/mosdns stop
/etc/init.d/passwall2 stop
/etc/init.d/udp2raw stop
/etc/init.d/udpspeeder stop
/etc/init.d/kcptun stop
/etc/init.d/dropbear stop

sysupgrade -r /etc/backup/VMwareX64_us_lanx0.tar.gz
rm -rf /etc/backup

uci commit system
/etc/init.d/dropbear start
uci commit firewall
/etc/init.d/firewall restart
uci commit dhcp
/etc/init.d/dnsmasq restart
uci commit network
/etc/init.d/network restart
/etc/init.d/udpspeeder start
/etc/init.d/udp2raw start
/etc/init.d/kcptun start
/etc/init.d/passwall2 start
uci commit mosdns
/etc/init.d/mosdns start
uci commit argon


exit 0
